{% set name = "pylhe" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylhe-{{ version }}.tar.gz
  sha256: 920c84f344f4e4dbcc080d11a51b4a9d34dec6edadc6feacd258732ba729a668

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >=1.13.0
    - hatch-vcs >=0.3.0
  run:
    - awkward >=1.2.0
    - python-graphviz >=0.12.0
    - particle >=0.16
    - python >=3.8
    - vector >=0.8.1

test:
  imports:
    - pylhe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/pylhe
  summary: A small package to get structured data out of Les Houches Event files
  dev_url: https://github.com/scikit-hep/pylhe
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - APN-Pucky
    - matthewfeickert
    - eduardo-rodrigues
    - lukasheinrich
