{% set name = "pylhe" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylhe-{{ version }}.tar.gz
  sha256: fe294dd2b058fb9b131b0db6b391c363aff4e8c1813205c6e706e65b0be772f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >=1.13.0
    - hatch-vcs >=0.3.0
  run:
    - awkward >=1.2.0
    - python-graphviz >=0.12.0
    - particle >=0.16
    - python >=3.8
    - vector >=0.8.1

test:
  imports:
    - pylhe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/pylhe
  summary: A small package to get structured data out of Les Houches Event files
  dev_url: https://github.com/scikit-hep/pylhe
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthewfeickert
    - eduardo-rodrigues
    - lukasheinrich
