{% set name = "pylhe" %}
{% set version = "1.0.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylhe-{{ version }}.tar.gz
  sha256: 28d49a82d01af071b5f97024533b89ad055d4374f96af2473f8d409dabbd6462

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.13.0
    - hatch-vcs >=0.3.0
  run:
    - awkward >=1.2.0
    - python-graphviz >=0.19
    - particle >=0.16
    - python >={{ python_min }}
    - vector >=0.8.1

test:
  imports:
    - pylhe
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scikit-hep/pylhe
  summary: A small package to get structured data out of Les Houches Event files
  dev_url: https://github.com/scikit-hep/pylhe
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - APN-Pucky
    - matthewfeickert
    - eduardo-rodrigues
    - lukasheinrich
    - conda-forge/scikit-hep
