{% set name = "pylhe" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylhe-{{ version }}.tar.gz
  sha256: 9802208be1d0bac449354e77019d7952dfbd7b6f88e9025e14f3d85b1af9e6c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=61.0.0
    - setuptools_scm >=7.0.1
  run:
    - awkward >=1.2.0
    - python-graphviz >=0.12.0
    - particle >=0.16
    - python >=3.7
    - vector >=0.8.1

test:
  imports:
    - pylhe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/pylhe
  summary: small package to get structured data out of Les Houches Event files
  dev_url: https://github.com/scikit-hep/pylhe
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthewfeickert
    - eduardo-rodrigues
    - lukasheinrich
