schema_version: 1

context:
  version: 2.0.0
  python_min: '3.10'

package:
  name: pylhe
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pylhe/pylhe-${{ version }}.tar.gz
  sha256: 36fee45bb13a79ff2067aecc6659d415e7519ddc972274260fa38114d502beec

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling >=1.27.0
    - hatch-vcs >=0.3.0
  run:
    - awkward >=2.7
    - python-graphviz >=0.19
    - particle >=0.26
    - python >=${{ python_min }}
    - vector >=1.6.3
    - h5py >=3.0
tests:
  - python:
      imports:
        - pylhe
      python_version:
        - ${{ python_min }}.*
        - '*'
      pip_check: true

about:
  summary: A lightweight Python interface to Les Houches Event files
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pylhe.readthedocs.io/
  repository: https://github.com/scikit-hep/pylhe
  documentation: https://pylhe.readthedocs.io/

extra:
  recipe-maintainers:
    - APN-Pucky
    - matthewfeickert
    - eduardo-rodrigues
    - lukasheinrich
    - conda-forge/scikit-hep
